# Generated by Django 4.2.7 on 2025-12-29 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_genres', models.JSONField(default=list, help_text='List of preferred music genres')),
                ('music_energy_mappings', models.JSONField(default=dict, help_text='Mapping of energy levels to music preferences')),
                ('preferred_color_palettes', models.JSONField(default=list, help_text='List of preferred color palettes')),
                ('theme_emotion_mappings', models.JSONField(default=dict, help_text='Mapping of emotions to theme preferences')),
                ('notification_frequency', models.IntegerField(default=5, help_text='Notification frequency in minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('wellness_reminder_interval', models.IntegerField(default=60, help_text='Wellness reminder interval in minutes', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)])),
                ('notification_tone', models.CharField(choices=[('sarcastic', 'Sarcastic'), ('motivational', 'Motivational'), ('balanced', 'Balanced'), ('minimal', 'Minimal')], default='balanced', help_text='Tone of notifications', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('suggestion_type', models.CharField(choices=[('music', 'Music Recommendation'), ('theme', 'Theme Suggestion'), ('task', 'Task Recommendation'), ('notification', 'Notification')], help_text='Type of AI suggestion', max_length=20)),
                ('emotion_context', models.JSONField(help_text='Emotion and energy data when suggestion was made')),
                ('suggestion_data', models.JSONField(help_text='Details of the suggestion that was made')),
                ('user_response', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('modified', 'Modified'), ('ignored', 'Ignored')], help_text='How the user responded to the suggestion', max_length=20)),
                ('alternative_preference', models.JSONField(blank=True, help_text="User's alternative preference when rejecting suggestion", null=True)),
                ('user_comment', models.TextField(blank=True, help_text='Optional user comment about the suggestion')),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedback',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='api_userfee_timesta_52d27f_idx'), models.Index(fields=['suggestion_type'], name='api_userfee_suggest_91c62d_idx'), models.Index(fields=['user_response'], name='api_userfee_user_re_8ebe91_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmotionReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emotions', models.JSONField(help_text="Dictionary of emotion probabilities (e.g., {'happy': 0.8, 'sad': 0.1})")),
                ('energy_level', models.FloatField(help_text='Energy level from 0.0 (low) to 1.0 (high)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('posture_score', models.FloatField(help_text='Posture quality score from 0.0 (poor) to 1.0 (excellent)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('blink_rate', models.FloatField(help_text='Blink rate in blinks per minute', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('confidence', models.FloatField(help_text='Detection confidence from 0.0 (low) to 1.0 (high)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'verbose_name': 'Emotion Reading',
                'verbose_name_plural': 'Emotion Readings',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='api_emotion_timesta_b2145d_idx'), models.Index(fields=['energy_level'], name='api_emotion_energy__4dc4a9_idx'), models.Index(fields=['confidence'], name='api_emotion_confide_04e731_idx')],
            },
        ),
    ]
