# Generated by Django 4.2.7 on 2025-12-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='music_energy_mappings',
            field=models.JSONField(blank=True, default=dict, help_text='Mapping of energy levels to music preferences'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='preferred_color_palettes',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred color palettes'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='preferred_genres',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred music genres'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='theme_emotion_mappings',
            field=models.JSONField(blank=True, default=dict, help_text='Mapping of emotions to theme preferences'),
        ),
    ]
