# Generated by Django 4.2.7 on 2025-12-29 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userpreferences_music_energy_mappings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title or description', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed task description')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Task priority level', max_length=10)),
                ('complexity', models.CharField(choices=[('simple', 'Simple'), ('moderate', 'Moderate'), ('complex', 'Complex'), ('creative', 'Creative')], default='moderate', help_text='Task complexity level', max_length=10)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='todo', help_text='Current task status', max_length=15)),
                ('complexity_score', models.FloatField(default=0.5, help_text='Calculated complexity score from 0.0 (simple) to 1.0 (complex)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('optimal_energy_level', models.FloatField(default=0.5, help_text='Optimal energy level for this task from 0.0 (low) to 1.0 (high)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('completion_energy_levels', models.JSONField(blank=True, default=list, help_text='List of energy levels when task was worked on')),
                ('user_energy_correlation', models.FloatField(default=0.0, help_text='Learned correlation between user energy and task performance (-1.0 to 1.0)', validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='Optional due date for the task', null=True)),
                ('estimated_duration', models.IntegerField(blank=True, help_text='Estimated duration in minutes', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('actual_duration', models.IntegerField(blank=True, help_text='Actual duration in minutes', null=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-priority', '-complexity_score', 'created_at'],
                'indexes': [models.Index(fields=['status'], name='api_task_status_2aef03_idx'), models.Index(fields=['priority'], name='api_task_priorit_175238_idx'), models.Index(fields=['complexity_score'], name='api_task_complex_e11c3f_idx'), models.Index(fields=['optimal_energy_level'], name='api_task_optimal_cf2637_idx'), models.Index(fields=['due_date'], name='api_task_due_dat_54ead5_idx'), models.Index(fields=['created_at'], name='api_task_created_9da793_idx')],
            },
        ),
    ]
