# Generated by Django 4.2.7 on 2025-12-29 15:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Genre name (e.g., 'rock', 'classical', 'electronic')", max_length=50, unique=True)),
                ('emotional_associations', models.JSONField(default=dict, help_text='Dictionary mapping emotions to strength scores (0.0-1.0)')),
                ('typical_energy_range', models.JSONField(default=list, help_text='List with [min_energy, max_energy] for this genre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Music Genre',
                'verbose_name_plural': 'Music Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='YouTubePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(help_text='YouTube playlist ID', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Playlist title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Playlist description')),
                ('channel_title', models.CharField(blank=True, help_text='Channel that created the playlist', max_length=100)),
                ('emotional_tags', models.JSONField(default=list, help_text='List of emotional tags for this playlist')),
                ('energy_level', models.FloatField(default=0.5, help_text='Average energy level of this playlist (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('user_rating', models.FloatField(blank=True, help_text='User rating from 0.0 to 5.0', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('play_count', models.IntegerField(default=0, help_text='Number of times this playlist was recommended/played')),
                ('acceptance_rate', models.FloatField(default=0.0, help_text='Rate at which user accepts this playlist (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('video_count', models.IntegerField(default=0, help_text='Number of videos in the playlist')),
                ('last_updated', models.DateTimeField(blank=True, help_text='When playlist data was last updated from YouTube', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this playlist is still available and active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, help_text='Associated music genres', to='api.musicgenre')),
            ],
            options={
                'verbose_name': 'YouTube Playlist',
                'verbose_name_plural': 'YouTube Playlists',
                'ordering': ['-acceptance_rate', '-user_rating', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MusicRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emotion_context', models.JSONField(help_text='Emotion data when recommendation was made')),
                ('energy_level', models.FloatField(help_text='Energy level when recommendation was made', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('recommendation_reason', models.TextField(help_text='Explanation of why this playlist was recommended')),
                ('confidence_score', models.FloatField(help_text='Confidence in this recommendation (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('user_response', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('ignored', 'Ignored'), ('modified', 'Modified')], help_text='How the user responded to this recommendation', max_length=20, null=True)),
                ('response_timestamp', models.DateTimeField(blank=True, help_text='When the user responded to the recommendation', null=True)),
                ('alternative_choice', models.JSONField(blank=True, help_text='Alternative music choice made by user', null=True)),
                ('recommended_playlist', models.ForeignKey(help_text='The playlist that was recommended', on_delete=django.db.models.deletion.CASCADE, to='api.youtubeplaylist')),
            ],
            options={
                'verbose_name': 'Music Recommendation',
                'verbose_name_plural': 'Music Recommendations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='youtubeplaylist',
            index=models.Index(fields=['youtube_id'], name='api_youtube_youtube_5da5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubeplaylist',
            index=models.Index(fields=['energy_level'], name='api_youtube_energy__6be6c7_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubeplaylist',
            index=models.Index(fields=['acceptance_rate'], name='api_youtube_accepta_da1efd_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubeplaylist',
            index=models.Index(fields=['is_active'], name='api_youtube_is_acti_1b132e_idx'),
        ),
        migrations.AddIndex(
            model_name='musicrecommendation',
            index=models.Index(fields=['timestamp'], name='api_musicre_timesta_bc839b_idx'),
        ),
        migrations.AddIndex(
            model_name='musicrecommendation',
            index=models.Index(fields=['user_response'], name='api_musicre_user_re_7ca184_idx'),
        ),
        migrations.AddIndex(
            model_name='musicrecommendation',
            index=models.Index(fields=['energy_level'], name='api_musicre_energy__f72f20_idx'),
        ),
    ]
