# Generated by Django 4.2.7 on 2025-12-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_musicgenre_youtubeplaylist_musicrecommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='cli_hook_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for CLI hooks and command execution'),
        ),
    ]
