#!/usr/bin/env node

/**
 * Virtual environment activation helper
 * This file is auto-generated by install-python-deps.js
 */

const path = require('path');
const os = require('os');

const isWindows = os.platform() === 'win32';
const venvPath = 'C:\\Users\\HP\\Downloads\\SideEye\\backend\\venv';

function getVenvPython() {
  return isWindows 
    ? path.join(venvPath, 'Scripts', 'python.exe')
    : path.join(venvPath, 'bin', 'python');
}

function getVenvPip() {
  return isWindows 
    ? path.join(venvPath, 'Scripts', 'pip.exe')
    : path.join(venvPath, 'bin', 'pip');
}

function getActivateScript() {
  return isWindows 
    ? path.join(venvPath, 'Scripts', 'activate.bat')
    : path.join(venvPath, 'bin', 'activate');
}

module.exports = {
  venvPath,
  getVenvPython,
  getVenvPip,
  getActivateScript
};
